name: amadeus
description: Unofficial dart library for Amadeus API
version: 0.0.4
homepage: https://github.com/ianmaciel/amadeus

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.6.0
  oauth2: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.1
  json_serializable: ^6.3.2
  lints: ^2.0.0
  mockito: ^5.3.1
  test: ^1.16.0
